CREATE TABLE `roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`)
)
  COLLATE='utf8_general_ci'
  ENGINE=InnoDB;

CREATE TABLE `users` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NULL DEFAULT NULL,
	`email` VARCHAR(255) NULL DEFAULT NULL,
	`login` VARCHAR(255) NOT NULL,
	`password` VARCHAR(255) NOT NULL,
	`role_id` INT(4) NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`),
	CONSTRAINT `users_roles`
	FOREIGN KEY (`role_id`)
	REFERENCES `roles` (`id`)
		ON UPDATE RESTRICT ON DELETE RESTRICT
)
	COLLATE='utf8_general_ci'
	ENGINE=InnoDB;

CREATE TABLE `accounts` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(45) NOT NULL,
	`debit` DECIMAL(8,2) NOT NULL DEFAULT '0.00',
	`creit` DECIMAL(8,2) NOT NULL DEFAULT '0.00',
	`user_id` INT NOT NULL DEFAULT '1',
	`currency_id` INT NOT NULL DEFAULT '1',
	PRIMARY KEY (`id`),
	CONSTRAINT `accounts_users`
	FOREIGN KEY (`user_id`)
	REFERENCES `users` (`id`)
		ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT `accounts_currencies`
	FOREIGN KEY (`currency_id`)
	REFERENCES `currencies` (`id`)
		ON UPDATE RESTRICT ON DELETE RESTRICT
)
	COLLATE='utf8_general_ci'
	ENGINE=InnoDB;

CREATE TABLE `currencies` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(45) NOT NULL DEFAULT '',
	`symbol` VARCHAR(10) NULL DEFAULT ''
)
	COLLATE='utf8_general_ci'
	ENGINE=InnoDB;
