<?php
/**
 * Created by PhpStorm.
 * User: klekot
 * Date: 14.10.2017
 * Time: 13:31
 */

namespace Main\controllers;

use \GF\Core\AbstractRestController as AbstractRestController;

class AccountsController extends AbstractRestController
{
    public function indexAction()
    {
        parent::indexAction(); // TODO: Change the autogenerated stub
    }

    public function show()
    {
        $data = array();
        if (isset($_REQUEST['id'])) {
            $account = \Account::find($_REQUEST['id']);
            $data[] = $this->getProperties($account);
        } else {
            $accounts = \Account::all();
            foreach ($accounts as $key => $account) {
                $data[] = $this->getProperties($account);
            }
        }

        parent::show($data);
    }
}